package ServantApp;


/**
* ServantApp/MyStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Servant.idl
* 18 декабря 2018 г. 5:55:54 MSK
*/

public final class MyStruct implements org.omg.CORBA.portable.IDLEntity
{
  public int x1 = (int)0;
  public int y1 = (int)0;
  public int x2 = (int)0;
  public int y2 = (int)0;
  public int g = (int)0;

  public MyStruct ()
  {
  } // ctor

  public MyStruct (int _x1, int _y1, int _x2, int _y2, int _g)
  {
    x1 = _x1;
    y1 = _y1;
    x2 = _x2;
    y2 = _y2;
    g = _g;
  } // ctor

} // class MyStruct
