package ServantApp;


/**
* ServantApp/ServantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Servant.idl
* 18 декабря 2018 г. 5:55:54 MSK
*/

public abstract class ServantPOA extends org.omg.PortableServer.Servant
 implements ServantApp.ServantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addPoints", new java.lang.Integer (0));
    _methods.put ("getNumber", new java.lang.Integer (1));
    _methods.put ("shutdown", new java.lang.Integer (2));
    _methods.put ("getPoints", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ServantApp/Servant/addPoints
       {
         int x1 = in.read_long ();
         int y1 = in.read_long ();
         int x2 = in.read_long ();
         int y2 = in.read_long ();
         int num = in.read_long ();
         this.addPoints (x1, y1, x2, y2, num);
         out = $rh.createReply();
         break;
       }

       case 1:  // ServantApp/Servant/getNumber
       {
         int $result = (int)0;
         $result = this.getNumber ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // ServantApp/Servant/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 3:  // ServantApp/Servant/getPoints
       {
         ServantApp.MyStruct $result = null;
         $result = this.getPoints ();
         out = $rh.createReply();
         ServantApp.MyStructHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ServantApp/Servant:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Servant _this() 
  {
    return ServantHelper.narrow(
    super._this_object());
  }

  public Servant _this(org.omg.CORBA.ORB orb) 
  {
    return ServantHelper.narrow(
    super._this_object(orb));
  }


} // class ServantPOA
