package ServantApp;


/**
* ServantApp/ServantHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Servant.idl
* 18 декабря 2018 г. 5:55:54 MSK
*/

abstract public class ServantHelper
{
  private static String  _id = "IDL:ServantApp/Servant:1.0";

  public static void insert (org.omg.CORBA.Any a, ServantApp.Servant that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ServantApp.Servant extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ServantApp.ServantHelper.id (), "Servant");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ServantApp.Servant read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServantStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ServantApp.Servant value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ServantApp.Servant narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServantApp.Servant)
      return (ServantApp.Servant)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServantApp._ServantStub stub = new ServantApp._ServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ServantApp.Servant unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ServantApp.Servant)
      return (ServantApp.Servant)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ServantApp._ServantStub stub = new ServantApp._ServantStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
