package ServantApp;


/**
* ServantApp/ServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Servant.idl
* 18 декабря 2018 г. 5:55:54 MSK
*/

public interface ServantOperations 
{
  void addPoints (int x1, int y1, int x2, int y2, int num);
  int getNumber ();
  void shutdown ();
  ServantApp.MyStruct getPoints ();
} // interface ServantOperations
