package ServantApp;

/**
* ServantApp/ServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Servant.idl
* 18 декабря 2018 г. 5:55:54 MSK
*/

public final class ServantHolder implements org.omg.CORBA.portable.Streamable
{
  public ServantApp.Servant value = null;

  public ServantHolder ()
  {
  }

  public ServantHolder (ServantApp.Servant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ServantApp.ServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ServantApp.ServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ServantApp.ServantHelper.type ();
  }

}
